// Unless explicitly stated otherwise all files in this repository are licensed under the MIT License.
//
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2021 Datadog, Inc.

package main

import (
	"context"
	_ "embed"
	"encoding/csv"
	"encoding/json"
	"io"
	"log"
	"os"
	"sort"
	"strings"

	"github.com/google/go-licenses/licenses"
	"github.com/google/licenseclassifier/v2"
)

const (
	outputFile = "LICENSE-3rdparty.csv"
)

var (
	importPaths = []string{"./internal/...", "./server/...", "./codec/..."}
	// "2.0" is a spurious entry generated by go-licenses v1.6.0 on Linux/amd64 when processing
	// modules with major version suffixes (e.g. k8s.io/klog/v2).
	// "golang.org/x/sys" and "golang.org/x/sys/unix" are excluded because go-licenses resolves
	// different subpackages on Linux vs macOS, causing platform-specific drift.
	ignoredPath = []string{
		"github.com/DataDog/temporal-large-payload-codec",
		"github.com/DataDog/temporal-large-payload-codec/codec",
		"github.com/DataDog/temporal-large-payload-codec/server",
		"2.0",
		"golang.org/x/sys",
		"golang.org/x/sys/unix",
	}
)

func main() {
	if err := execute(); err != nil {
		log.Fatal(err)
	}
}

type Component struct {
	Origin    string `json:"origin"`
	License   string `json:"license"`
	Copyright string `json:"copyright"`
}

//go:embed overrides.json
var componentOverrides []byte

func execute() error {
	classifier, err := licenses.NewClassifier(0.9)
	if err != nil {
		return err
	}

	f, err := os.OpenFile(outputFile, os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0755)
	if err != nil {
		return err
	}
	defer f.Close()

	ctx := context.Background()

	libs, err := licenses.Libraries(ctx, classifier, false, ignoredPath, importPaths...)
	if err != nil {
		return err
	}

	components := map[string]Component{}
	var overrides map[string]Component
	if err := json.Unmarshal(componentOverrides, &overrides); err != nil {
		return err
	}

	for _, lib := range libs {
		var component Component
		var licenseUrl string
		if lib.LicensePath != "" {
			// Parse copyright
			if b, err := os.ReadFile(lib.LicensePath); err == nil {
				component.Copyright = licenseclassifier.CopyrightHolder(string(b))
			}
			// Parse license type
			if ln, _, err := classifier.Identify(lib.LicensePath); err == nil {
				component.License = ln
			}
			// Parse license URL
			if lURL, err := lib.FileURL(ctx, lib.LicensePath); err == nil {
				licenseUrl = lURL
			}
		}
		if licenseUrl != "" {
			component.Origin = strings.Split(licenseUrl, "/blob/")[0]
		}

		components[lib.Name()] = component
	}

	for k, v := range overrides {
		components[k] = v
	}

	return writeComponents(f, components)
}

func writeComponents(w io.Writer, components map[string]Component) error {
	c := csv.NewWriter(w)
	defer c.Flush()

	if err := c.Write([]string{"Component", "Origin", "License", "Copyright"}); err != nil {
		return err
	}

	// Sort component names
	var keys []string
	for k, _ := range components {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, k := range keys {
		component := components[k]
		if err := c.Write([]string{k, component.Origin, component.License, component.Copyright}); err != nil {
			return err
		}
	}

	return nil
}
