name: LPS

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          check-latest: true

      - name: Print Go version
        run: go version

      - name: Build binary
        run: go build -o lps cmd/server/main.go

      - name: Run tests
        run: go test ./...

      - name: Lint code
        run: |
          gofmt -l .
          test -z $(gofmt -l .)

      - name: Validate 3rd party dependencies
        run: |
          go run internal/tools/licensecheck/main.go
          if ! git diff --quiet LICENSE-3rdparty.csv; then
            echo "LICENSE-3rdparty.csv is out of date. Please run 'go run ./internal/tools/licensecheck' and commit the changes."
            exit 1
          fi
