name: LPS CI

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.work'
          check-latest: true

      - name: Print Go version
        run: go version

      - name: Build binary
        run: make build

      - name: Run tests
        run: make test

      - name: Lint code (codec)
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.10.1
          working-directory: codec

      - name: Lint code (server)
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.10.1
          working-directory: server

      - name: Validate 3rd party dependencies
        run: make check_license

      - name: Validate Go header files
        run: make check_copyright
