name: LPS

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.x'

      - name: Print Go version
        run: go version

      - name: Build binary
        run: go build -o lps cmd/server/main.go

      - name: Run tests
        run: go test ./...

      - name: Lint code
        run: |
          gofmt -l .
          test -z $(gofmt -l .)
