name: LPS Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          generateReleaseNotes: true
