name: LPS Releases

on:
  push:
    tags:
      - '*'
permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          config-file: '.github/workflows/release-please-config.json'
          manifest-file: '.github/workflows/release-please-manifest.json'
          target-branch: 'mortadha.teffaha/split_server_and_codec_dependencies'